export const expenses = [
  // November 2024
  {
    id: 1,
    date: '2024-11-05',
    description: 'Thanksgiving Groceries',
    amount: 278.5,
    category: 'Food & Dining',
    merchant: 'Whole Foods',
  },
  {
    id: 2,
    date: '2024-11-12',
    description: 'Winter Coat',
    amount: 189.99,
    category: 'Shopping',
    merchant: 'North Face',
  },
  {
    id: 3,
    date: '2024-11-18',
    description: 'Pre-Black Friday Shopping',
    amount: 345.75,
    category: 'Shopping',
    merchant: 'Best Buy',
  },
  {
    id: 4,
    date: '2024-11-22',
    description: 'Family Movie Night',
    amount: 65.25,
    category: 'Entertainment',
    merchant: 'AMC Theaters',
  },
  {
    id: 5,
    date: '2024-11-28',
    description: 'Black Friday Shopping',
    amount: 520.0,
    category: 'Shopping',
    merchant: 'Various Stores',
  },

  // December 2024
  {
    id: 6,
    date: '2024-12-02',
    description: 'Holiday Decorations',
    amount: 145.5,
    category: 'Shopping',
    merchant: 'Home Depot',
  },
  {
    id: 7,
    date: '2024-12-08',
    description: 'Winter Concert Tickets',
    amount: 210.0,
    category: 'Entertainment',
    merchant: 'Ticketmaster',
  },
  {
    id: 8,
    date: '2024-12-15',
    description: 'Holiday Gifts',
    amount: 485.75,
    category: 'Gifts & Donations',
    merchant: 'Various Stores',
  },
  {
    id: 9,
    date: '2024-12-20',
    description: 'Christmas Dinner',
    amount: 195.25,
    category: 'Food & Dining',
    merchant: 'Local Grocery',
  },
  {
    id: 10,
    date: '2024-12-28',
    description: "New Year's Eve Party",
    amount: 230.0,
    category: 'Entertainment',
    merchant: 'Liquor Store',
  },
  {
    id: 11,
    date: '2024-12-31',
    description: 'Annual Gym Membership',
    amount: 599.99,
    category: 'Health & Fitness',
    merchant: 'Fitness World',
  },

  // January 2025
  {
    id: 12,
    date: '2025-01-03',
    description: 'New Year Health Supplements',
    amount: 87.5,
    category: 'Health & Fitness',
    merchant: 'GNC',
  },
  {
    id: 13,
    date: '2025-01-08',
    description: 'Winter Sales Shopping',
    amount: 245.0,
    category: 'Shopping',
    merchant: "Macy's",
  },
  {
    id: 14,
    date: '2025-01-14',
    description: 'Home Office Upgrade',
    amount: 899.99,
    category: 'Shopping',
    merchant: 'Apple Store',
  },
  {
    id: 15,
    date: '2025-01-20',
    description: 'Ski Trip Weekend',
    amount: 725.5,
    category: 'Travel',
    merchant: 'Airbnb',
  },
  {
    id: 16,
    date: '2025-01-25',
    description: 'Winter Car Maintenance',
    amount: 320.75,
    category: 'Transportation',
    merchant: 'AutoZone',
  },
  {
    id: 17,
    date: '2025-01-30',
    description: 'Monthly Utilities',
    amount: 235.5,
    category: 'Housing',
    merchant: 'Electric Company',
  },

  // February 2025
  {
    id: 18,
    date: '2025-02-05',
    description: "Valentine's Day Gift",
    amount: 175.0,
    category: 'Gifts & Donations',
    merchant: 'Jewelry Store',
  },
  {
    id: 19,
    date: '2025-02-10',
    description: 'Tax Preparation Services',
    amount: 250.0,
    category: 'Other',
    merchant: 'Accounting Firm',
  },
  {
    id: 20,
    date: '2025-02-14',
    description: "Valentine's Day Dinner",
    amount: 185.5,
    category: 'Food & Dining',
    merchant: 'Fine Dining Restaurant',
  },
  {
    id: 21,
    date: '2025-02-18',
    description: 'Online Course Subscription',
    amount: 129.99,
    category: 'Education',
    merchant: 'Coursera',
  },
  {
    id: 22,
    date: '2025-02-22',
    description: 'Weekend Getaway',
    amount: 430.25,
    category: 'Travel',
    merchant: 'Hotel Chain',
  },
  {
    id: 23,
    date: '2025-02-28',
    description: 'Monthly Utilities',
    amount: 240.5,
    category: 'Housing',
    merchant: 'Electric Company',
  },

  // March 2025
  {
    id: 24,
    date: '2025-03-05',
    description: 'Spring Wardrobe Update',
    amount: 350.75,
    category: 'Shopping',
    merchant: 'Zara',
  },
  {
    id: 25,
    date: '2025-03-10',
    description: 'Home Improvement Project',
    amount: 520.0,
    category: 'Housing',
    merchant: 'IKEA',
  },
  {
    id: 26,
    date: '2025-03-15',
    description: "St. Patrick's Day Celebration",
    amount: 85.0,
    category: 'Food & Dining',
    merchant: 'Irish Pub',
  },
  {
    id: 27,
    date: '2025-03-20',
    description: 'Spring Break Trip',
    amount: 1250.0,
    category: 'Travel',
    merchant: 'Airline',
  },
  {
    id: 28,
    date: '2025-03-25',
    description: 'Concert Tickets',
    amount: 175.0,
    category: 'Entertainment',
    merchant: 'Ticketmaster',
  },
  {
    id: 29,
    date: '2025-03-28',
    description: 'Monthly Utilities',
    amount: 230.0,
    category: 'Housing',
    merchant: 'Electric Company',
  },
  {
    id: 30,
    date: '2025-03-31',
    description: 'Quarterly Car Insurance',
    amount: 420.5,
    category: 'Transportation',
    merchant: 'Insurance Company',
  },
];
