export const expenses = [
  {
    id: 1,
    date: '2023-05-01',
    description: 'Groceries',
    amount: 120.5,
    category: 'Food',
    merchant: 'Whole Foods',
  },
  {
    id: 2,
    date: '2023-05-03',
    description: 'Gas station',
    amount: 45.0,
    category: 'Transportation',
    merchant: 'Shell',
  },
  {
    id: 3,
    date: '2023-05-05',
    description: 'Movie tickets',
    amount: 30.0,
    category: 'Entertainment',
    merchant: 'Cineplex',
  },
  {
    id: 4,
    date: '2023-05-10',
    description: 'Internet bill',
    amount: 75.99,
    category: 'Utilities',
    merchant: 'Comcast',
  },
  {
    id: 5,
    date: '2023-05-15',
    description: 'Dinner',
    amount: 65.75,
    category: 'Food',
    merchant: 'Olive Garden',
  },
  {
    id: 6,
    date: '2023-05-18',
    description: 'Office supplies',
    amount: 32.5,
    category: 'Work',
    merchant: 'Staples',
  },
  {
    id: 7,
    date: '2023-05-20',
    description: 'Gym membership',
    amount: 45.99,
    category: 'Health',
    merchant: 'Fitness World',
  },
  {
    id: 8,
    date: '2023-05-22',
    description: 'Rideshare',
    amount: 18.75,
    category: 'Transportation',
    merchant: 'Uber',
  },
  {
    id: 9,
    date: '2023-05-25',
    description: 'Books',
    amount: 42.35,
    category: 'Education',
    merchant: 'Barnes & Noble',
  },
  {
    id: 10,
    date: '2023-05-28',
    description: 'Concert tickets',
    amount: 150.0,
    category: 'Entertainment',
    merchant: 'Ticketmaster',
  },
  {
    id: 11,
    date: '2023-05-30',
    description: 'Clothes',
    amount: 88.5,
    category: 'Shopping',
    merchant: 'H&M',
  },
  {
    id: 12,
    date: '2023-06-01',
    description: 'Mobile phone bill',
    amount: 65.0,
    category: 'Utilities',
    merchant: 'Verizon',
  },
  {
    id: 13,
    date: '2023-06-05',
    description: 'Lunch',
    amount: 15.75,
    category: 'Food',
    merchant: 'McDonalds',
  },
  {
    id: 14,
    date: '2023-06-10',
    description: 'Office supplies',
    amount: 32.5,
    category: 'Work',
    merchant: 'Staples',
  },
  {
    id: 15,
    date: '2023-06-15',
    description: 'Dinner',
    amount: 65.75,
    category: 'Food',
    merchant: 'Olive Garden',
  },
];
